# Generated by Django 2.2.1 on 2019-06-17 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('website', models.URLField(max_length=250, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_number', models.IntegerField(default=0)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='modules/thumbnails')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Module',
                'verbose_name_plural': 'Modules',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('basicdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biology.BasicData')),
                ('file_upload', models.FileField(null=True, upload_to='articles')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='articles/thumbnails')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ('title', 'description', 'updated'),
            },
            bases=('biology.basicdata',),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('basicdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biology.BasicData')),
                ('file_upload', models.FileField(null=True, upload_to='journals')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='journals/thumbnails')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journals',
                'ordering': ('title', 'description', 'updated'),
            },
            bases=('biology.basicdata',),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.IntegerField(default=0)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='modules/units/thumbnails')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('file_upload', models.FileField(upload_to='modules/units')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biology.Module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ('unit_number', 'title', 'description', 'updated'),
            },
        ),
        migrations.AddField(
            model_name='basicdata',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biology.Unit', verbose_name='Unit'),
        ),
    ]
