# Generated by Django 2.2.1 on 2019-06-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='units_url',
            field=models.URLField(null=True),
        ),
    ]
