# Generated by Django 2.2.1 on 2019-06-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicdata',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
