# Generated by Django 2.2.1 on 2019-06-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='modules/thumbnails'),
        ),
    ]
