# Generated by Django 2.2.1 on 2019-06-11 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biology', '0002_module_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ('unit_number', 'title', 'description', 'updated'), 'verbose_name': 'Unit', 'verbose_name_plural': 'Units'},
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('basicdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biology.BasicData')),
                ('file_upload', models.FileField(null=True, upload_to='articles')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='articles/thumbnails')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ('title', 'description', 'updated'),
            },
            bases=('biology.basicdata',),
        ),
    ]
