# Generated by Django 2.2.1 on 2019-06-19 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biology', '0002_module_units_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicdata',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='biology.Module', verbose_name='Module'),
        ),
    ]
