# Generated by Django 2.2.1 on 2019-06-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biology', '0002_basicdata_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
