# Generated by Django 2.2.1 on 2019-06-11 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biology', '0003_auto_20190611_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('basicdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='biology.BasicData')),
                ('file_upload', models.FileField(null=True, upload_to='journals')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='journals/thumbnails')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journals',
                'ordering': ('title', 'description', 'updated'),
            },
            bases=('biology.basicdata',),
        ),
    ]
