# Generated by Django 2.2.1 on 2019-06-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biology', '0003_unit_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
