# Generated by Django 2.2.1 on 2019-06-13 17:39

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('biology', '0004_module_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='module',
            managers=[
                ('unit_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='unit',
            managers=[
                ('unit_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
