# Generated by Django 2.2.1 on 2019-06-13 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biology', '0005_auto_20190613_1039'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='module',
            managers=[
            ],
        ),
    ]
