# Generated by Django 2.2.1 on 2019-06-13 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biology', '0006_auto_20190613_1056'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='unit',
            managers=[
            ],
        ),
    ]
