# Generated by Django 2.2.1 on 2019-06-27 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surgical', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='module',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='unit',
            managers=[
            ],
        ),
    ]
